#!/bin/bash

function command_install {

    function help {

        echo -e "Install nginx ."

    }

    function php_patch_ini {

        php_ini_path=`php -i | grep 'Loaded Configuration File' | awk '{print $5}'`

        if [ $php_ini_path = "(none)" ] 
        then
            echo "No php ini loaded, making /etc/php.ini"
            cp /etc/php.ini.default /etc/php.ini
            php_ini_path='/etc/php.ini'
        fi

        php_ini_backup="$php_ini_path.backup"

        cp $php_ini_path $php_ini_backup
        sed 's%;date.timezone =.*%date.timezone = "Europe/Paris"%' $php_ini_backup > $php_ini_path

        php_fpm_path=`php-fpm -i | grep 'fpm.config' | awk '{print $3}'`
        if [ $php_fpm_path = "no" ]
        then
            echo "No php-fpm.conf loaded, making /etc/php-fpm.conf"
            cp /etc/php-fpm.conf.default /etc/php-fpm.conf
            php_fpm_path='/etc/php-fpm.conf'
        fi

        php_fpm_backup="$php_fpm_path.backup"

        cp $php_fpm_path $php_fpm_backup
        sed 's%;error_log.*%error_log = /usr/local/var/log/php-fpm/php-fpm.log%' $php_fpm_backup > $php_fpm_path
    }

    function get_nginx {

        curl ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.tar.gz > pcre.tar.gz
        tar -xf pcre.tar.gz
        cd pcre-8.38
        ./configure --prefix=/usr/local
        make
        make install
        cd ..
        rm -r pcre-8.38
        rm pcre.tar.gz

        curl http://nginx.org/download/nginx-1.11.3.tar.gz > nginx.tar.gz
        tar -xf nginx.tar.gz
        cd nginx-1.11.3
        ./configure --prefix=/usr/local/nginx
        make
        make install
        cd ..
        rm -r nginx-1.11.3
        rm nginx.tar.gz
    }

    function process {

        set -e
        
        if is_command_exist php-fpm
        then
            verbose 1 "php-fmp installed"
        else
            verbose 1 "Fatal : php-fpm not installed"
            exit 1
        fi
        
        if is_command_exist /usr/local/nginx/sbin/nginx; then
            verbose 1 "nginx already installed. Skip"
        else
            get_nginx
        fi

        pulsion update_config

        mkdir -p /usr/local/var/log/php-fpm

        verbose 1 "patching php.ini timezone"

        exesudo php_patch_ini
    }
}


function command_update_config {

    function help {

        echo -e "Update nginx"

    }

    function process {

        set -e

        echo "Gettings last nginx config"

        rm /usr/local/nginx/conf/nginx.conf

        mkdir -p /usr/local/nginx/conf/logs
        mkdir -p /usr/local/nginx/conf/sites-available
        mkdir -p /usr/local/nginx/conf/sites-enabled
        mkdir -p /usr/local/nginx/conf/conf.d
        mkdir -p /usr/local/nginx/conf/ssl

        curl -L https://raw.githubusercontent.com/arnaudhe/config/master/nginx/nginx.conf -o /usr/local/nginx/conf/nginx.conf
        curl -L https://raw.githubusercontent.com/arnaudhe/config/master/nginx/conf.d/php-fpm -o /usr/local/nginx/conf/conf.d/php-fpm
        curl -L https://raw.githubusercontent.com/arnaudhe/config/master/nginx/sites-available/default -o /usr/local/nginx/conf/sites-available/default
        
        ln -sfv /usr/local/nginx/conf/sites-available/default /usr/local/nginx/conf/sites-enabled/default

    }
}

function command_start {

    function help {

        echo -e "Start php-fcm and nginx"

    }

    function process {

        verbose 1 "Starting php-fcm..."
        php-fpm
        verbose 1 "Starting nginx"
        /usr/local/nginx/sbin/nginx
    }
}

function command_stop {

    function help {

        echo -e "Stop php-fcm and nginx"

    }

    function process {
        
        verbose 1 "Stopping php-fcm..."
        for pid in `lsof -Pni4 | grep php-fpm | awk {'print $2'}`
        do 
            kill -9 $pid
        done
        verbose 1 "Stopping nginx"
        /usr/local/nginx/sbin/nginx -s stop

    }
}

function command_restart {

    function help {

        echo -e "Restart PHP-FCM and NGINX"

    }

    function process {

        pulsion stop
        pulsion start

    }
}

function command_doctor {

    function help {

        echo -e "Check install sanity"

    }

    function process {

        set -e   #stop if error

        if is_command_exist /usr/local/nginx/sbin/nginx
        then
            verbose 1 "nginx conf auto-test"
            /usr/local/nginx/sbin/nginx -T > /dev/null
        else
            verbose 1 "nginx not installed"
            exit 1
        fi

        if is_command_exist php-fpm
        then
            verbose 1 "php-fpm conf auto-test"
            php-fpm --test
        else
            verbose 1 "php-fpm not installed"
            exit 1
        fi

        pulsion start

        sleep 2  #let services time to init

        verbose 1 "Test of php-fcm"
        lsof -Pni4 | grep LISTEN | grep php

        verbose 1 "Test of nginx"
        code=`curl -s -o /dev/null -w "%{http_code}" http://localhost:8080`
        if [ $code = "200" ]; then
            verbose 1 "Connection Ok (200)"
            verbose 1 " "
            exit 0
        else
            verbose 1 "Connection error (http $code)"
            exit 1
        fi
    }
}

function command_logs_access {

    function help {

        echo -e "Nginx logs access"

    }

    function process {

        tail -250f /usr/local/nginx/logs/access.log
    }
}

function command_logs_error {

    function help {

        echo -e "Nginx logs errors"

    }

    function process {

        tail -250f /usr/local/nginx/logs/error.log
    }
}

function command_logs_default_access {

    function help {

        echo -e "Nginx logs access on virtual host default"

    }

    function process {

        tail -250f /usr/local/nginx/logs/default.access.log
    }
}